## RESNET-18

The following notebook is based on this `pytorch` tutorial
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

- https://pytorch.org/vision/main/models/generated/torchvision.models.resnet18.html
- https://arxiv.org/pdf/1512.03385.pdf

In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

In [3]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/james/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100.0%


In [25]:
data = torch.rand(1, 3, 64, 64)
data.shape

torch.Size([1, 3, 64, 64])

In [26]:
labels = torch.rand(1, 1000)
labels.shape

torch.Size([1, 1000])

In [27]:
prediction = model(data)
prediction.shape

torch.Size([1, 1000])

In [28]:
loss = (prediction - labels).sum()
loss

tensor(-498.7974, grad_fn=<SumBackward0>)

In [29]:
loss.backward()

In [32]:
# loss.grad

/Users/james/miniconda3/envs/ds_env/lib/python3.9/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484620427/work/build/aten/src/ATen/core/TensorBody.h:482.)
  return self._grad


In [33]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [34]:
optim

SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)

In [35]:
optim.step()

In [44]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
a

tensor([2., 3.], requires_grad=True)

In [45]:
Q = 3*a**3 - b**2
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [46]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [47]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
